### ISSUE TITLE
ActiveSupport conflicts with String function redefinitions

### ISSUE THREAD

**Issue by patcable** [aviator/aviator#131]
Hi Mark,

First, thanks a bunch for making Aviator -- it definitely has saved me from writing a ton of OpenStack binding code in Ruby. When working with OpenStack, any time saver is a win.

I'm having a bit of an issue using Aviator with Rails(4.2.1 on Ruby 2.2.2) however, and have hit a dead end and was hoping you may be able to help.

I think that `String#camelize`, `String#constantize` and `String#underscore` are redefined in a way that doesn't work with Rails. When I use the Aviator gem in my project, some of my other gems will start to have issues, such as throwing `uninitialized constant Devise::SessionsController` or `wrong constant name FontAwesome/rails/iconHelper`. Oddly enough (at least to me) they show as routing errors.

To address this I wrapped the definitions a check to see if ActiveSupport was around, since it seems that this has happened with other gems as well:
```ruby
class String
 
  unless defined?(ActiveSupport::CoreExtensions) || defined?(ActiveSupport::Inflector)
    unless instance_methods.include? 'camelize'
      ...
    end
 
    unless instance_methods.include? 'constantize'
      ...
    end
 
    unless instance_methods.include? 'underscore'
      ...
    end
  end
 end
```

This fixes the issue where other rubygems (like Devise and Font-Awesome) broke because of the redefinitions, but seems to raise `wrong constant name openstack` on the last line of my code where I try to use Aviator to authenticate against Keystone:

```ruby
openstack = Aviator::Session.new(
          :config_file => Rails.root.join('config','aviator.yml').to_s,
          :environment => :demo
        )

openstack.authenticate
```
I'm able to get past it if I modify the file to remove the `:camelize` method:
```ruby
class String
  unless instance_methods.include? 'constantize'
        ...
  end

  unless instance_methods.include? 'underscore'
    ...
  end
end
```
However, this still breaks Devise. 

I totally understand this is a Rails related issue, so if this is outside of scope for you I totally understand. But if you have a good hint to help fix this I'd be happy to test and submit a PR as well.

**Comment by relaxdiego** [comment]
@patcable thanks for using Aviator and for this issue. Have you tried loading/requiring Aviator last? The only other solution I can think of is for Aviator to avoid the monkeypatching altogether. I see only around 30 instances when these methods are called so the change should not be huge.

**Comment by patcable** [comment]
Hmm -- so, I only throw the 'require aviator' into the specific controller that requires it -- it's not called at the application controller layer or anything farther up the stack. I think that's the latest I can call it.

Indeed, I think this may be a case of changing those 30 instances. Happy to help with it -- or at least learn a bit more about what the cause is by looking at the diff =)

**Comment by relaxdiego** [comment]
There's also a quick fix option of just commenting out the entire monkypatching done by Aviator while waiting for me to replace those calls.

**Comment by patcable** [comment]
Ah, to be clear - commenting out the whole of `strings.rb`? I think the `unless defined?(ActiveSupport::CoreExtensions) || defined?(ActiveSupport::Inflector)` I had experimented with does that, but I gave commentting everything out a go and ran into the same issue as well - `wrong constant name openstack` if I recall correctly.

**Comment by relaxdiego** [comment]
@patcable sounds like camelize is implemented differently in ActiveSupport now. Anyway, I've made the change and is waiting in its own PR at #132. Could you try that out before I merge it?

**Comment by patcable** [comment]
@relaxdiego works great! thanks so much for taking the time to do this -- I really appreciate it!

**Comment by relaxdiego** [comment]
No worries! Thanks for your patience and for taking time to report this.
