### ISSUE TITLE
Use of 'hash' identifier perilous.

### ISSUE THREAD

**Issue by keithrbennett** [aviator/aviator#135]
Use of the identifier 'hash' is perilous.  It is used in the Hashish class.  The problem is that it overrides the 'hash' method in Kernel.  This Kernel method is used as a higher-performance-than-== first pass at seeing if objects differ by classes such as Set and (!) Hash. I suggest never using 'hash' as an identifier unless you know that the scope will be extremely limited.  Here's an irb session that illustrates the point:

```
2.2.1 :003 > h = Hashish.new
 => #<Hashish:0x007fca511e2648 @hash={}>
2.2.1 :004 > Set.new.add h
TypeError: no implicit conversion of Hash into Integer
	from /Users/kbennett/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/set.rb:290:in `add'
	from (irb):4
	from /Users/kbennett/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
2.2.1 :008 > {}[h] = 3
TypeError: no implicit conversion of Hash into Integer
	from (irb):8
	from /Users/kbennett/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

**Comment by relaxdiego** [comment]
Thank you, @keithrbennett, for reporting this bug. I agree that this is a poor name choice and quite a silly oversight. I will have a fix shortly.

**Comment by relaxdiego** [comment]
Merged to master.
